# Generated by Django 5.0.6 on 2024-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('coordinates', models.TextField()),
                ('type_object', models.CharField(max_length=128)),
                ('administrative_district', models.CharField(max_length=128)),
                ('municipal_district', models.CharField(max_length=128)),
                ('house_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=128)),
                ('unom', models.IntegerField()),
            ],
        ),
    ]
