# Generated by Django 5.0.6 on 2024-06-15 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='unom',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField()),
                ('material', models.IntegerField()),
                ('purpose', models.IntegerField()),
                ('house_class', models.IntegerField()),
                ('unom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinates.house', to_field='unom')),
            ],
        ),
    ]
